apiVersion: v1
kind: Namespace
metadata:
  name: mahjong

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mahjong
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 0x9.pw/mahjong-frontend:0.1.3
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mahjong
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 0x9.pw/mahjong-backend:0.1.2
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mahjong
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mahjong
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mahjong
  namespace: mahjong
  labels:
    app: mahjong
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: mahjong.0x9.pw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /v1/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
  tls:
  - secretName: mahjong-general-tls
    hosts:
    - mahjong.0x9.pw
